### ISSUE TITLE
submodules or submodule

### ISSUE THREAD

**Issue by StormingMoose** [Circu1tI0N3rd/rtl8188eus-rpi#1]
Instructions crashed  when I tried to use the submodules  in the statement
git submodules update --init

I used submodule instead and am typing this as I am waiting for the "Cloning into ... " process to finish.

**Comment by StormingMoose** [comment]
Then it was done and the rest of the commands went smoothly except it did not see the usb dongle when i rebooted.
![usbwifidongle](https://user-images.githubusercontent.com/81178656/187246141-3448124a-8998-4366-9bb7-0d66964aa377.jpg)

**Comment by StormingMoose** [comment]
On the latest release of buster installed August 28 2022.  Using a wireless Compute Module 4 on a waveshare I/O board.  The usb was activated via the config.txt in the boot directory according the waveshare directions before attempting to use the dongle.

**Comment by Circu1tI0N3rd** [comment]
Sorry for the late response.  This repo was an attempt to compile the module outside of my Raspberry Pi 1B running Wheezy.  Apparently the Raspbian kernel cross-compiling method changed and I haven't been around much.  The best practise is to stick with the latest cross-compiling instruction while I review my repo.

Certain branches were broken, so that's explained of that submodule situation (as far as I know the `submodule --init` command's still correct).
